# Uncomment the next line to define a global platform for your project
platform :ios, "10.0"
workspace 'GraphNotificationsSample'

target 'GraphNotificationsSample' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!
    
    # This is the main Graph Notifications SDK. It includes all the functionality needed for Receiving and interacting with notifications
    pod 'GraphNotificationsLibrary', '~>0.0.6'
    pod 'MSAL'
    pod 'PromiseKit'


        
    # force the sub specs in the array below to use swift version 3.2
    # https://github.com/mxcl/PromiseKit/issues/722
    post_install do |installer| 
        installer.pods_project.targets.each do |target|
            if ['PromiseKit'].include? target.name
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = '4.2'
                end
            end
        end
    end
end
